import type { NextPage } from 'next';
import Head from 'next/head';
import { Cards } from '../components/Cards';
import { useWallet } from '../hooks';
import { fetchBuildSpaceNfts, fetchLWD3Nfts } from '../utils';

const Home: NextPage = () => {
	const { currentAccount, connectWallet } = useWallet();

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="App">
				<div className="container w-[80%] m-auto mt-6 mb-5">
					{/* Heading */}
					<p className="m-0 text-center font-bold text-3xl text-white">
						Learn Web3 DAO
					</p>
					<p className="text-gray-400 m-1 mt-0 text-center">
						Proof of Knowledge NFTs
					</p>
					<Cards fetchNFTs={fetchLWD3Nfts} />
				</div>
				<div className="container w-[80%] m-auto mt-6">
					{/* Heading */}
					<p className="m-0 text-center font-bold text-3xl text-white">
						BuildSpace
					</p>
					<p className="text-gray-400 m-1 mt-0 text-center">
						Proof of Knowledge NFTs
					</p>
					<Cards fetchNFTs={fetchBuildSpaceNfts} />
				</div>
			</div>
		</>
	);
};

export default Home;
