import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useWallet } from '../hooks';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
	const { currentAccount, connectWallet } = useWallet();

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className="text-red-400">
					Welcome to <a href="https://nextjs.org">Next.js!</a>
				</h1>
				<button onClick={connectWallet}>Connect Wallet</button>
			</main>
		</div>
	);
};

export default Home;
