import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useAccount } from 'wagmi';
import { Cards } from '../components/Cards';
import { useWallet } from '../hooks';
import { fetchBuildSpaceNfts, fetchLWD3Nfts } from '../utils';

const Home: NextPage = () => {
	const { isConnected } = useAccount();

	return (
		<>
			<Head>
				<title>POK Viewer</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			{!isConnected ? (
				<div className="flex flex-col items-center justify-center h-screen">
					<h2 className="mt-2 mb-2 text-6xl 2xl:text-8xl text-white font-bold font-heading text-center">
						Learn Web 3 Dao X BuildSpace
					</h2>
					<p className="text-yellow-500 text-4xl font-bold font-heading text-center mb-4">
						View your Proof of Knowledge NFTs
					</p>
					<ConnectButton />
				</div>
			) : (
				<div className="App">
					<div className="container w-[80%] m-auto mt-6 mb-5">
						{/* Heading */}
						<div className="flex justify-center items-center">
							<p className="m-0 text-center font-bold text-3xl text-white flex-1 ml-[15.25rem]">
								Learn Web3 DAO
							</p>
							<div className="justify-self-end">
								<ConnectButton />
							</div>
						</div>
						<p className="text-gray-400 m-1 mt-0 text-center">
							Proof of Knowledge NFTs
						</p>
						<Cards fetchNFTs={fetchLWD3Nfts} />
					</div>
					<div className="container w-[80%] m-auto mt-6">
						{/* Heading */}
						<p className="m-0 text-center font-bold text-3xl text-white">
							BuildSpace
						</p>
						<p className="text-gray-400 m-1 mt-0 text-center">
							Proof of Knowledge NFTs
						</p>
						<Cards fetchNFTs={fetchBuildSpaceNfts} />
					</div>
				</div>
			)}
		</>
	);
};

export default Home;
